#!/usr/bin/env bash
# Using Bash script to install nginx and set up a listening port to 80

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
service nginx start
