#!/usr/bin/env bash
#loops from 1 to 10, printing "bad luck", "good luck" and "Best School" for 4th, 8th, and other iteration respectively 
count=1
while [ $count -le 10 ]; do
	if [ $count -eq 4 ]; then
		echo "bad luck"
	elif [ $count -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
fi
	((count++))
done
