#!/usr/bin/env bash
#loops from 1 to 20 and displays specific words and characters at 4th, 9th and 17th iteration respectively
count=1
while [ $count -le 20 ]; do
	if [ $count -eq 4 ]; then
		echo "$count"
		echo "bad luck from China"
	elif [ $count -eq 9 ]; then
		echo "$count"
		echo "bad luck from Japan"
	elif [ $count -eq 17 ]; then
		echo "$count"
		echo "bad luck from Italy"
	else
		echo "$count"
fi
	((count++))
done
	
