#!/usr/bin/env bash
#displays content of a directory in list format
for file_name in *; do
	if [ -f "$file_name" ]; then
		actual_name=$(echo "$file_name" | cut -d '-' -f 2-)
		echo "${actual_name}"
	fi
done
