#!/usr/bin/env bash
# allow nginx to run as the nginx user, listen to all active IPs on port 8080
pkill apache
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i 's/# user www-data/user nginx/g' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
